name: swing_train

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "* 11 * * 4"  # Every Thursday 6:00 PM Malaysia Time (UTC+8 => UTC 11:45AM)

  workflow_dispatch:  # ম্যানুয়ালি চালাতে পারবে

permissions:
  contents: write  # কমিট এবং পুশ করার অনুমতি দেয়

jobs:
  analyze_stocks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # সম্পূর্ণ git হিস্ট্রি ফেচ করে

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install torch==2.3.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
        pip install -r requirements.txt

    - name: Check if it's a biweekly run (even week)
      id: week-check
      run: |
        week_num=$(date +%U)
        echo "Current week number: $week_num"
        if [ $((10#$week_num % 2)) -ne 0 ]; then
          echo "Skipping this run, not an even week."
          exit 0
        fi
        echo "Proceeding with training this week."

    - name: Run Python script
      if: ${{ success() }}
      env:
        MONGO_URL: ${{ secrets.MONGO_URI }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        hf_token: ${{ secrets.HF_TOKEN }}
      run: python ./main_train.py
